env:
  node: true
  jest: true
plugins:
  - jest
extends:
  - airbnb-base
  - plugin:jest/recommended
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules: 
  no-console: 0
  import/extensions: 0
